### ISSUE TITLE
Using unowned reference in Presenter class

### ISSUE THREAD

**Issue by hahuja** [infinum/ios-viper-xcode-templates#39]
I have a scenario where user goes to next page, by pushing view controller. The next page has a collectionView and an API call, if user goes to next page, API is called and based on response collectionView is reloaded. Now, if user clicks back button very quickly(before response comes), so view controller is destroyed from memory, but since the view reference was unowned `private unowned let view: KBPlusMemberDetailViewInterface`, it still exists. Now, user is on the previous page and the API gives data on next page, and self.view.collectionView.reloadData() is called on the next page(which is not in memory anymore), but since self is destroyed, so the app is crashed. How can we solve this?

**Comment by Truba** [comment]
Hi @hahuja ,

I'm really sorry that it took us this long to answer.

What you have just described here is memory leek. Your api call should not have a strong reference to your presenter / interactor / view. You should weakify self in the callback. 

Also you should cancel the api call when the view / presenter / interactor delocates since you don't want to waste resources.

**Comment by kvaljeva** [comment]
Hi @hahuja,

is this issue still apparent or did you manage to fix this afterwards? If it was fixed, I would like to close the issue. If it's not, please, don't hesitate to continue the discussion and we'll try to help. 🙂

**Comment by mazmik25** [comment]
i think this relates to my PR before

https://github.com/infinum/iOS-VIPER-Xcode-Templates/pull/40
We've tried to weakify the `presenter` inside the callback. but it still got this issue. that's why everytime we generate the files, we always weakify the `presenter`

**Comment by goranbrl** [comment]
Closing this one due to inactivity.
