### ISSUE TITLE
I clicked on the makefile executable of version 2, and it deleted all the files from my documents folder

### ISSUE THREAD

**Issue by rideflag-minh-huynh** [infinum/ios-viper-xcode-templates#41]
yes, my documents folder on my Mac is now completely empty.  I might have tried installing incorrectly but why would it delete all my documents in my documents folder? 

[iOS-VIPER-Xcode-Templates-master.zip](https://github.com/infinum/iOS-VIPER-Xcode-Templates/files/5803992/iOS-VIPER-Xcode-Templates-master.zip)

**Comment by Truba** [comment]
Hi @rideflag-minh-huynh ,

I'm sorry to hear that.
This is the complete script in the Makefile:
```bash
XCODE_USER_TEMPLATES_DIR=~/Library/Developer/Xcode/Templates/File\ Templates
VIPER_TEMPLATES_DIR=VIPER\ Templates

install_templates:
	rm -R -f $(XCODE_USER_TEMPLATES_DIR)/$(VIPER_TEMPLATES_DIR)
	mkdir -p $(XCODE_USER_TEMPLATES_DIR)
	cp -R -f $(VIPER_TEMPLATES_DIR) $(XCODE_USER_TEMPLATES_DIR)

uninstall_templates:
	rm -R $(XCODE_USER_TEMPLATES_DIR)/$(VIPER_TEMPLATES_DIR)
```

Since the path for your documents should be something like: `/Users/<your_username>/Documents`, and this script only clears the data in: `/Library/Developer/Xcode/Templates/File Templates/VIPER Templates` I'm honestly not sure how would that even happen.

Have you tried editing the Makefile, or can you please provide us with some info on how you tried installing the template?

**Comment by rideflag-minh-huynh** [comment]
I got the template from a coworker.  I never touched the makefile.  other than clicking on it.  it opened in my terminal and started to do its thing. everything is in that zip file I sent.

**Comment by Truba** [comment]
Hi @rideflag-minh-huynh ,

I'm sorry, but I don't see how what you are describing could have happened, unless `XCODE_USER_TEMPLATES_DIR` on your computer somehow links to user documents, which should never happen 😞

**Comment by goranbrl** [comment]
Closing this one due to inactivity.
